[package]
name = "new-tokio-smtp"
version = "0.1.0"
authors = ["Philipp Korber <philippkorber@gmail.com>"]

[dependencies]
futures = "0.1"
bytes = "0.4"
tokio = "0.1"
tokio-io = "0.1"
tokio-tls = "0.1.4"
native-tls = "0.1.5"

[features]
default = []
mock_support = []
mock_impl = ["mock_support"]
